import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HydrateTheme } from "@/components/hydrate/HydrateTheme";
import { HydrateToaster } from "@/components/hydrate/HydrateToaster";
import { Auth } from "@/typedata/auth/auth";
import { getAuthFromSever } from "@/lib/getAuthFromServer";
import HydrateAuth from "@/components/hydrate/HydrateAuth";
import { Suspense } from "react";
import NextTopLoader from "nextjs-toploader";
import { cookies } from "next/headers";
import { themeConfig } from "@/config/theme";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const auth: Auth = await getAuthFromSever();
  const theme = (await cookies()).get(themeConfig.cookieKey)?.value;

  return (
    <html lang="en" className={`${theme || "dark"} scroll-smooth`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HydrateToaster />

        {/* <HydrateTheme /> */}

        <Suspense fallback={null}>
          <NextTopLoader color="var(--foreground)" height={2} />
        </Suspense>

        <HydrateAuth auth={auth} />
        {children}
      </body>
    </html>
  );
}
